#Build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# 2. fázis: A futtató környezet (Run)
FROM eclipse-temurin:17-jre
WORKDIR /app
# Átmásoljuk a lefordított .jar fájlt az első fázisból
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]