spring.application.name=FleetFalcon

# address of the database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ff_db}
spring.datasource.username=${DB_USER:ff_user}
spring.datasource.password=${DB_PASSWORD:secret}

# SQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# driver
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL commands to console
spring.jpa.show-sql=true

# to shut the warning up
spring.jpa.open-in-view=false

# Clears the DB every time the application stops
# Normally set to =update
spring.jpa.hibernate.ddl-auto=update

# Session Configuration for HttpOnly Cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}
server.servlet.session.cookie.same-site=${COOKIE_SAMESITE:Lax}
server.servlet.session.timeout=30m
spring.session.store-type=none

configuration.setAllowedOrigins(Arrays.asList("http://localhost:4200", "https://fleetfalcon-frontend.vercel.app"));
